#define yy_create_buffer pp_create_buffer
#define yy_delete_buffer pp_delete_buffer
#define yy_scan_buffer pp_scan_buffer
#define yy_scan_string pp_scan_string
#define yy_scan_bytes pp_scan_bytes
#define yy_flex_debug pp_flex_debug
#define yy_init_buffer pp_init_buffer
#define yy_flush_buffer pp_flush_buffer
#define yy_load_buffer_state pp_load_buffer_state
#define yy_switch_to_buffer pp_switch_to_buffer
#define yyin ppin
#define yyleng ppleng
#define yylex pplex
#define yyout ppout
#define yyrestart pprestart
#define yytext pptext

#line 19 "pplex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
static yyconst short int yy_accept[265] =
    {   0,
        0,    0,    6,    6,    0,    0,    0,    0,    0,    0,
       62,   60,   52,   53,   60,   60,   55,   56,   60,   60,
       60,   57,   60,   57,   60,   60,   57,   57,   57,   57,
       57,   57,   57,   57,   57,    1,    2,    6,    5,    6,
        1,    2,   14,    8,   14,   14,   14,   14,    1,    2,
       34,   18,   19,   34,   34,   22,   23,   34,   34,   34,
       31,   20,   31,   34,   34,   31,   31,   31,   31,   31,
       31,   31,    1,    2,   41,   35,   36,   41,   41,   41,
       41,   41,   38,   41,   38,   41,   41,   38,    1,    2,
       53,    0,   59,    0,    3,    0,   58,   52,   54,   57,

       57,   53,    7,   57,   57,   57,   57,   57,   57,   57,
       57,   57,    1,    1,    2,    6,    3,    1,    1,    2,
        0,    0,    0,   11,    0,   19,    0,   33,    0,    0,
       32,   18,   31,   31,   21,   24,   25,   26,   31,   31,
       31,   36,    0,   40,    0,    0,   39,   35,   38,   38,
       37,    3,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,    1,    3,    1,    0,    0,    0,    0,   27,
       31,   31,   31,   57,   15,   57,   57,   57,   57,   57,
       57,   57,   57,    0,    0,   13,    0,   31,   31,   31,
       57,   57,   48,   57,   57,   57,   57,   57,   49,   50,

       51,   12,    0,    0,   31,   31,   31,   42,   57,   57,
       57,   48,   57,   57,   57,   57,   57,   49,   50,   51,
       10,    9,   31,   31,   31,   57,   57,   57,   16,   57,
        4,   17,   57,   31,   31,   31,   57,   57,   57,   57,
       47,   29,   31,   28,   57,   57,   57,   57,   30,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   43,
       46,   45,   44,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   14,   14,   14,   14,   14,   14,    1,   18,    1,
       19,   20,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       21,   38,   39,   40,   41,   21,   42,   43,   44,   21,
        1,    1,    1,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   21,   38,   39,   40,   41,   21,   42,   43,
       44,   21,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    1,    3,    3,    3,    3,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst short int yy_base[285] =
    {   0,
        0,   37,   44,   45,   46,   47,   86,   43,  130,   49,
      704,  779,  779,  697,  692,  668,  779,  779,  643,   49,
      173,  181,  189,  197,   65,  642,   59,  167,  174,   60,
      190,  182,  206,  210,  213,  637,    0,    0,  779,  629,
      604,    0,  779,  779,  603,   45,  580,  574,  580,    0,
      779,  779,  588,  569,  551,  779,  779,  531,  214,  244,
      252,  260,  268,   76,  525,  168,  243,  222,  223,  253,
      269,  230,  523,    0,  779,  779,  522,  514,  510,  489,
      282,  298,  306,  314,  322,  179,  475,  231,  466,    0,
      473,  469,  779,  465,    0,  330,  338,  779,  458,  239,

      346,  450,  779,  293,  331,  339,  276,  347,  299,  354,
      357,  360,    0,    0,    0,    0,    0,    0,    0,    0,
      401,  396,  405,  779,  375,  409,  384,  779,  372,  368,
      382,  779,  294,  390,  779,  307,  315,  383,  391,  377,
      399,  362,  303,  779,  288,  403,  412,  779,  363,  423,
      779,    0,  413,  364,  420,  431,  435,  438,  439,  442,
      446,  447,    0,    0,    0,  264,  255,  247,  214,  450,
      454,  455,  459,  462,  467,  470,  473,  480,  481,  485,
      490,  489,  507,  223,  216,  779,  213,  494,  498,  495,
      504,  516,  519,  520,  526,  525,  529,  536,  537,  542,

      545,  779,  187,  193,  550,  551,  555,  558,  559,  562,
      566,  779,  567,  572,  573,  576,  577,  779,  779,  779,
      779,  779,  580,  584,  587,  591,  596,  597,  601,  606,
      610,  619,  620,  623,  624,  627,  628,  631,  632,  635,
      636,  640,  643,  644,  648,  657,  658,  664,  667,  670,
      671,  676,  675,  679,  680,  683,  687,  698,  702,  697,
      703,  707,  714,  779,  727,  730,  733,  736,  212,  739,
      742,  745,  748,  751,  754,  757,   81,  760,  763,   77,
      766,  769,  772,  775
    } ;

static yyconst short int yy_def[285] =
    {   0,
      264,    1,  265,  265,  266,  266,  264,    7,  264,    9,
      264,  264,  264,  264,  267,  268,  264,  264,  264,  264,
      264,  269,  264,  269,  264,  264,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  270,  271,  272,  264,  272,
      273,  274,  264,  264,  264,  264,  264,  264,  270,  271,
      264,  264,  264,  275,  276,  264,  264,  264,  264,  264,
      277,  264,  277,  264,  264,  277,  277,  277,  277,  277,
      277,  277,  270,  271,  264,  264,  264,  278,  279,  264,
      264,  264,  280,  264,  280,  264,  264,  280,  270,  271,
      264,  267,  264,  268,  281,  264,  264,  264,  264,  269,

      269,  264,  264,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  270,  282,  271,  272,  283,  273,  284,  274,
      264,  264,  264,  264,  264,  264,  275,  264,  276,  264,
      264,  264,  277,  277,  264,  277,  277,  277,  277,  277,
      277,  264,  278,  264,  279,  264,  264,  264,  280,  280,
      264,  281,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  282,  283,  284,  264,  264,  264,  264,  277,
      277,  277,  277,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  264,  264,  264,  264,  277,  277,  277,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,

      269,  264,  264,  264,  277,  277,  277,  269,  269,  269,
      269,  264,  269,  269,  269,  269,  269,  264,  264,  264,
      264,  264,  277,  277,  277,  269,  269,  269,  269,  269,
      269,  269,  269,  277,  277,  277,  269,  269,  269,  269,
      269,  277,  277,  277,  269,  269,  269,  269,  277,  269,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  269,  269,    0,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264
    } ;

static yyconst short int yy_nxt[824] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   12,   24,   24,   24,   24,   25,   12,   26,
       27,   28,   27,   29,   30,   31,   27,   27,   27,   32,
       27,   27,   27,   27,   27,   27,   33,   34,   35,   27,
       27,   27,   27,   27,   36,   39,   39,   44,   44,   37,
       73,   40,   41,   45,   49,   74,   89,   42,   96,   50,
       96,   90,   97,   97,   97,   97,   98,  102,  264,  264,
      264,  264,   46,   46,  121,   47,   47,  132,  126,  149,
      122,  106,  123,  133,   48,   48,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   51,   63,

       63,   63,   63,   64,   65,   51,   66,   66,   67,   66,
       66,   66,   66,   66,   66,   68,   66,   66,   66,   66,
       66,   69,   70,   71,   72,   66,   66,   66,   66,   66,
       75,   76,   77,   78,   79,   75,   75,   80,   81,   82,
       83,   84,   75,   85,   85,   85,   85,   86,   87,   75,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   98,   99,  264,  264,  264,  264,
      148,  142,   96,  264,   96,  264,   97,   97,   97,   97,
       96,  264,   96,  264,  101,  101,  101,  101,   96,  264,

       96,  264,   97,   97,   97,   97,   96,  104,   96,  105,
      101,  101,  101,  101,  100,  264,  108,  264,  222,  264,
      107,  264,  264,  130,  264,  130,  221,  131,  131,  131,
      131,  264,  264,  264,  264,  110,  204,  203,  111,  264,
      264,  264,  264,  109,  112,  132,  126,  202,  264,  138,
      264,  187,  264,  130,  264,  130,  137,  131,  131,  131,
      131,  130,  264,  130,  264,  134,  134,  134,  134,  130,
      141,  130,  186,  131,  131,  131,  131,  130,  264,  130,
      264,  134,  134,  134,  134,  264,  136,  264,  185,  184,
      139,  146,  144,  146,  140,  147,  147,  147,  147,  148,

      142,  156,  264,  264,  264,  264,  144,  146,  264,  146,
      264,  147,  147,  147,  147,  146,  264,  146,  264,  150,
      150,  150,  150,  146,  264,  146,  264,  147,  147,  147,
      147,  146,  153,  146,  159,  150,  150,  150,  150,   96,
      264,   96,  264,   97,   97,   97,   97,   96,  264,   96,
      264,   97,   97,   97,   97,   96,  264,   96,  264,  101,
      101,  101,  101,  264,  142,  264,  264,  154,  264,  264,
      157,  264,  264,  264,  264,  264,  128,  130,  155,  130,
      161,  131,  131,  131,  131,  158,  264,  128,  264,  162,
      160,  130,  264,  130,  264,  131,  131,  131,  131,  130,

      264,  130,  264,  134,  134,  134,  134,  175,  264,  170,
      264,  126,  146,  172,  146,  169,  147,  147,  147,  147,
      171,  146,  264,  146,  264,  147,  147,  147,  147,  264,
      168,  264,  146,  167,  146,  173,  150,  150,  150,  150,
      264,  174,  264,  166,  264,  176,  264,  264,  264,  264,
      264,  264,  102,  264,  177,  264,  264,  264,  264,  264,
       99,  264,  180,  264,  264,  264,  264,  178,  264,   93,
      264,  264,   93,  264,  181,   91,  264,  179,  264,  264,
      192,  264,  264,  183,  264,  114,  182,  189,  188,  264,
      264,  264,  264,  151,  264,  190,  264,  191,  264,  264,

      264,  264,  195,  264,  264,  264,  264,  264,   95,  264,
      196,  197,  193,  264,  144,  264,  264,  144,  264,  206,
      194,  199,  200,  201,  142,  264,  198,  264,  264,  264,
      212,  264,  207,  205,  264,  264,  264,  264,  264,  209,
      264,  208,  114,  135,  213,  264,  264,  264,  218,  210,
       95,  264,  216,  219,  264,  128,  220,  211,  214,  264,
      264,  264,  264,  215,  264,  217,  264,  264,  264,  264,
      264,  264,  128,  264,  224,  264,  264,  264,  264,  223,
      225,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      126,  264,  229,  264,  226,  264,  264,  227,  264,  114,

      264,  232,  264,  228,  230,  264,  264,  264,  264,  125,
      264,  231,  264,  235,  234,  264,  233,  264,  124,  264,
      238,  264,   95,  119,  237,  236,  239,  240,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  117,  264,
      242,  264,  264,  264,  264,  264,  114,  264,  243,  264,
      246,  103,   95,  241,  245,  244,  264,  264,  264,  264,
      249,  247,   93,  264,  248,  264,  264,  250,  264,  264,
      264,  264,  264,  251,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  253,  264,   93,  264,  252,  264,   91,

      255,  256,  254,  264,  258,  259,  264,  264,  264,  264,
      257,  264,  264,  264,  264,  264,  264,  260,  264,  264,
      264,  261,  262,  264,  264,  264,  263,   38,   38,   38,
       43,   43,   43,   92,  264,   92,   94,  264,   94,  113,
      264,  113,  115,  264,  115,  116,  264,  116,  118,  264,
      118,  120,  264,  120,  127,  264,  127,  129,  264,  129,
      143,  264,  143,  145,  264,  145,  152,  264,  152,  163,
      264,  163,  164,  264,  164,  165,  264,  165,   11,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264
    } ;

static yyconst short int yy_chk[824] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    3,    4,    5,    6,    2,
        8,    3,    4,    5,    6,    8,   10,    4,   20,    6,
       20,   10,   20,   20,   20,   20,   25,   25,   27,   30,
       27,   30,    5,    6,   46,    5,    6,   64,   64,  280,
       46,   30,   46,  277,    5,    6,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   21,   21,   28,   66,   28,   66,
       86,   86,   21,   29,   21,   29,   21,   21,   21,   21,
       22,   32,   22,   32,   22,   22,   22,   22,   23,   31,

       23,   31,   23,   23,   23,   23,   24,   28,   24,   29,
       24,   24,   24,   24,  269,   33,   32,   33,  204,   34,
       31,   34,   35,   59,   35,   59,  203,   59,   59,   59,
       59,   68,   69,   68,   69,   34,  187,  185,   35,   72,
       88,   72,   88,   33,   35,   60,   60,  184,  100,   69,
      100,  169,   67,   60,   67,   60,   68,   60,   60,   60,
       60,   61,   70,   61,   70,   61,   61,   61,   61,   62,
       72,   62,  168,   62,   62,   62,   62,   63,   71,   63,
       71,   63,   63,   63,   63,  107,   67,  107,  167,  166,
       70,   81,  145,   81,   71,   81,   81,   81,   81,   82,

       82,  107,  104,  133,  104,  133,  143,   82,  109,   82,
      109,   82,   82,   82,   82,   83,  136,   83,  136,   83,
       83,   83,   83,   84,  137,   84,  137,   84,   84,   84,
       84,   85,  104,   85,  109,   85,   85,   85,   85,   96,
      105,   96,  105,   96,   96,   96,   96,   97,  106,   97,
      106,   97,   97,   97,   97,  101,  108,  101,  108,  101,
      101,  101,  101,  110,  142,  110,  111,  105,  111,  112,
      108,  112,  149,  154,  149,  154,  129,  130,  106,  130,
      111,  130,  130,  130,  130,  108,  140,  127,  140,  112,
      110,  131,  138,  131,  138,  131,  131,  131,  131,  134,

      139,  134,  139,  134,  134,  134,  134,  154,  141,  138,
      141,  126,  146,  140,  146,  125,  146,  146,  146,  146,
      139,  147,  153,  147,  153,  147,  147,  147,  147,  155,
      123,  155,  150,  122,  150,  141,  150,  150,  150,  150,
      156,  153,  156,  121,  157,  155,  157,  158,  159,  158,
      159,  160,  102,  160,  156,  161,  162,  161,  162,  170,
       99,  170,  159,  171,  172,  171,  172,  157,  173,   94,
      173,  174,   92,  174,  160,   91,  175,  158,  175,  176,
      176,  176,  177,  162,  177,   89,  161,  172,  171,  178,
      179,  178,  179,   87,  180,  173,  180,  174,  182,  181,

      182,  181,  179,  188,  190,  188,  190,  189,   80,  189,
      180,  181,  177,  191,   79,  191,  183,   78,  183,  189,
      178,  183,  183,  183,   77,  192,  182,  192,  193,  194,
      193,  194,  190,  188,  196,  195,  196,  195,  197,  192,
      197,  191,   73,   65,  194,  198,  199,  198,  199,  192,
       58,  200,  197,  200,  201,   55,  201,  192,  195,  205,
      206,  205,  206,  196,  207,  198,  207,  208,  209,  208,
      209,  210,   54,  210,  206,  211,  213,  211,  213,  205,
      207,  214,  215,  214,  215,  216,  217,  216,  217,  223,
       53,  223,  213,  224,  209,  224,  225,  210,  225,   49,

      226,  216,  226,  211,  214,  227,  228,  227,  228,   48,
      229,  215,  229,  224,  223,  230,  217,  230,   47,  231,
      227,  231,   45,   41,  226,  225,  228,  230,  232,  233,
      232,  233,  234,  235,  234,  235,  236,  237,  236,  237,
      238,  239,  238,  239,  240,  241,  240,  241,   40,  242,
      234,  242,  243,  244,  243,  244,   36,  245,  235,  245,
      238,   26,   19,  233,  237,  236,  246,  247,  246,  247,
      243,  239,   16,  248,  240,  248,  249,  245,  249,  250,
      251,  250,  251,  246,  253,  252,  253,  252,  254,  255,
      254,  255,  256,  248,  256,   15,  257,  247,  257,   14,

      251,  252,  250,   11,  254,  255,  260,  258,  260,  258,
      253,  259,  261,  259,  261,    0,  262,  256,  262,    0,
        0,  257,  258,  263,    0,  263,  259,  265,  265,  265,
      266,  266,  266,  267,    0,  267,  268,    0,  268,  270,
        0,  270,  271,    0,  271,  272,    0,  272,  273,    0,
      273,  274,    0,  274,  275,    0,  275,  276,    0,  276,
      278,    0,  278,  279,    0,  279,  281,    0,  281,  282,
        0,  282,  283,    0,  283,  284,    0,  284,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pplex.l"
#define INITIAL 0
/*							-*- c -*-
 * Copyright (C) 2001-2007 Keisuke Nishida
 * Copyright (C) 2007 Roger While
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, 51 Franklin Street, Fifth Floor
 * Boston, MA 02110-1301 USA
 */
#define YY_NEVER_INTERACTIVE 1
#line 28 "pplex.l"

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef	HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <ctype.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "cobc.h"
#include "ppparse.h"

static int within_comment = 0;
static size_t newline_count = 0;
static int inside_bracket = 0;
static int quotation_mark = 0;
static int consecutive_quotation = 0;
static int last_line_1 = -1;
static int last_line_2 = -1;

static struct cb_replace_list *current_replace_list = NULL;

static struct cb_text_list *text_queue = NULL;

static struct copy_info {
	struct copy_info	*next;
	char			*file;
	int			line;
	int			replacing;
	int			quotation_mark;
	YY_BUFFER_STATE		buffer;
} *copy_stack = NULL;

#define YY_INPUT(buf,result,max_size) result = ppinput (buf, max_size);
static int ppinput (char *buf, int max_size);
static void ppecho (const char *text);

static void switch_to_buffer (int lineno, char *filename, YY_BUFFER_STATE buffer);

#define PROCESS_STATE 1
#define DIRECTIVE_STATE 2
#define COPY_STATE 3
#define PSEUDO_STATE 4

#line 726 "pplex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 80 "pplex.l"





#line 886 "pplex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 265 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 779 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 86 "pplex.l"
case 2:
#line 87 "pplex.l"
case 3:
YY_RULE_SETUP
#line 87 "pplex.l"
{ ppecho (" "); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 89 "pplex.l"
{ BEGIN PROCESS_STATE; }
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 92 "pplex.l"
{ BEGIN INITIAL; unput ('\n'); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 93 "pplex.l"
{ cb_warning (_("PROCESS statement is ignored")); }
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 96 "pplex.l"
{ BEGIN DIRECTIVE_STATE; return DIRECTIVE; }
	YY_BREAK

case 8:
YY_RULE_SETUP
#line 99 "pplex.l"
{ BEGIN INITIAL; unput ('\n'); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 100 "pplex.l"
{ return SOURCE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 101 "pplex.l"
{ return FORMAT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "pplex.l"
{ return IS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "pplex.l"
{ return FIXED; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "pplex.l"
{ return FREE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "pplex.l"
{ }
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 108 "pplex.l"
{ BEGIN COPY_STATE; return COPY; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 109 "pplex.l"
{ BEGIN COPY_STATE; return COPY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 110 "pplex.l"
{ BEGIN COPY_STATE; return REPLACE; }
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 113 "pplex.l"
{ ECHO; cb_source_line++; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "pplex.l"
{ /* ignore */ }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "pplex.l"
{ BEGIN INITIAL; return '.'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "pplex.l"
{ BEGIN PSEUDO_STATE; return EQEQ; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 117 "pplex.l"
{ return '('; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 118 "pplex.l"
{ return ')'; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "pplex.l"
{ return BY; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "pplex.l"
{ return IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "pplex.l"
{ return OF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "pplex.l"
{ return OFF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "pplex.l"
{ return SUPPRESS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 124 "pplex.l"
{ return PRINTING; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 125 "pplex.l"
{ return REPLACING; }
	YY_BREAK
case 31:
#line 127 "pplex.l"
case 32:
#line 128 "pplex.l"
case 33:
#line 129 "pplex.l"
case 34:
YY_RULE_SETUP
#line 129 "pplex.l"
{ pplval.s = strdup (yytext); return TOKEN; }
	YY_BREAK


case 35:
YY_RULE_SETUP
#line 133 "pplex.l"
{ ECHO; cb_source_line++; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 134 "pplex.l"
{ pplval.s = strdup (" "); return TOKEN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 135 "pplex.l"
{ BEGIN COPY_STATE; return EQEQ; }
	YY_BREAK
case 38:
#line 137 "pplex.l"
case 39:
#line 138 "pplex.l"
case 40:
#line 139 "pplex.l"
case 41:
YY_RULE_SETUP
#line 139 "pplex.l"
{ pplval.s = strdup (yytext); return TOKEN; }
	YY_BREAK

case 42:
#line 143 "pplex.l"
case 43:
#line 144 "pplex.l"
case 44:
#line 145 "pplex.l"
case 45:
#line 146 "pplex.l"
case 46:
#line 147 "pplex.l"
case 47:
YY_RULE_SETUP
#line 147 "pplex.l"
{
	/* these words are treated as comments */
	if (cb_verify (cb_author_paragraph, yytext)) {
		/* skip comments until the end of line */
		int c;

		within_comment = 1;
		while ((c = input ()) != EOF) {
			if (c == '\n') {
				break;
			}
		}
		unput (c);
	}
}
	YY_BREAK
case 48:
#line 164 "pplex.l"
case 49:
#line 165 "pplex.l"
case 50:
#line 166 "pplex.l"
case 51:
YY_RULE_SETUP
#line 166 "pplex.l"
{
	/* these words are comments in IBM COBOL */
	if (cb_verify (cb_eject_statement, yytext)) {
		/* do nothing for now */
	} else {
		ECHO;
	}
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 175 "pplex.l"
{ ppecho ("\n"); cb_source_line++; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 176 "pplex.l"
{ ppecho (" "); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 177 "pplex.l"
{
	if (inside_bracket) {
		ppecho (", ");
	} else {
		ppecho (" ");
	}
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 185 "pplex.l"
{ inside_bracket++; ppecho ("("); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 186 "pplex.l"
{ inside_bracket--; ppecho (")"); }
	YY_BREAK
case 57:
#line 189 "pplex.l"
case 58:
#line 190 "pplex.l"
case 59:
#line 191 "pplex.l"
case 60:
YY_RULE_SETUP
#line 191 "pplex.l"
{ ppecho (yytext); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PROCESS_STATE):
case YY_STATE_EOF(DIRECTIVE_STATE):
case YY_STATE_EOF(COPY_STATE):
case YY_STATE_EOF(PSEUDO_STATE):
#line 193 "pplex.l"
{
	struct copy_info *p = copy_stack;

	yy_delete_buffer (YY_CURRENT_BUFFER);

	/* Terminate at the end of all input */
	if (p->next == NULL) {
		within_comment = 0;
		newline_count = 0;
		inside_bracket = 0;
		current_replace_list = NULL;
		text_queue = NULL;
		copy_stack = NULL;
		quotation_mark = 0;
		consecutive_quotation = 0;
		last_line_1 = -1;
		last_line_2 = -1;
		yyterminate ();
	}

	/* Close the current file */
	fclose (ppin);

	/* Switch to the last buffer */
	if (p->replacing) {
		pp_set_replace_list (NULL);
	}
	switch_to_buffer (p->line, p->file, p->buffer);
	quotation_mark = p->quotation_mark;

	copy_stack = p->next;
	free (p);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 227 "pplex.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1293 "pplex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 265 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 265 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 264);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 227 "pplex.l"


void
pp_set_replace_list (struct cb_replace_list *list)
{
	current_replace_list = list;
}

static void
switch_to_buffer (int line, char *file, YY_BUFFER_STATE buffer)
{
	char	*p;

	cb_source_line = line;
	cb_source_file = strdup (file);
	for (p = cb_source_file; *p; p++) {
		if (*p == '\\') {
			*p = '/';
		}
	}
	yy_switch_to_buffer (buffer);
	fprintf (yyout, "# %d \"%s\"\n", line, cb_source_file);
}

int
ppopen (char *name, struct cb_replace_list *replace_list)
{
	struct copy_info *p;

	for (; newline_count > 0; newline_count--) {
		ungetc ('\n', ppin);
	}

	/* Open the copy file */
	ppin = fopen (name, "rb");
	if (!ppin) {
		if (cb_source_file) {
			cb_error (_("%s: %s"), name, strerror (errno));
		} else {
			perror (name);
		}
		return -1;
	}

	/* Add to dependency list */
	if (cb_depend_file) {
		cb_depend_list = cb_text_list_add (cb_depend_list, name);
	}

	/* Preserve the current buffer */
	p = cobc_malloc (sizeof (struct copy_info));
	p->line = cb_source_line;
	p->file = cb_source_file;
	p->replacing = replace_list ? 1 : 0;
	p->buffer = YY_CURRENT_BUFFER;
	p->quotation_mark = quotation_mark;
	p->next = copy_stack;
	copy_stack = p;

	/* Switch to new buffer */
	if (replace_list) {
		pp_set_replace_list (replace_list);
	}
	switch_to_buffer (1, name, yy_create_buffer (ppin, YY_BUF_SIZE));
	return 0;
}

int
ppcopy (char *name, const char *lib, struct cb_replace_list *replace_list)
{
	struct cb_text_list	*il;
	struct cb_text_list	*el;
	struct stat		st;
	char			buff1[COB_MEDIUM_BUFF];
	char			buff2[COB_MEDIUM_BUFF];

	if (lib) {
		sprintf (buff1, "%s/%s", lib, name);
		name = buff1;
	}

	/* Find the file */
	if (stat (name, &st) == -1) {
		for (el = cb_extension_list; el; el = el->next) {
			sprintf (buff2, "%s%s", name, el->text);
			if (stat (buff2, &st) == 0) {
				name = buff2;
				return ppopen (name, replace_list);
			}
		}
		if (name[0] != '/') {
			for (il = cb_include_list; il; il = il->next) {
				for (el = cb_extension_list; el; el = el->next) {
					sprintf (buff2, "%s/%s%s", il->text, name, el->text);
					if (stat (buff2, &st) == 0) {
						name = buff2;
						return ppopen (name, replace_list);
					}
				}
			}
		}
		cb_error (_("%s: %s"), name, strerror (errno));
		return -1;
	}

	return ppopen (name, replace_list);
}

/*
 * Read line
 */

static int
ppinput (char *buff, int max_size)
{

	int	i, n;
	int	continuation = 0;
	char	*bp;
	char	line[COB_MEDIUM_BUFF];

start:
	/* read a line */
	memset (line, 0, sizeof (line));
	if (fgets (line, COB_MEDIUM_BUFF, ppin) == NULL) {
		if (newline_count == 0) {
			return 0;
		}
		memset (buff, '\n', newline_count);
		buff[newline_count] = 0;
		newline_count = 0;
		return strlen (buff);
	}

	/* normalize and copy the line into the buffer */
	n = 0;
	for (i = 0; line[i]; i++) {
		switch (line[i]) {
		case '\t':
			/* tab expansion */
			buff[n++] = ' ';
			while (n % cb_tab_width != 0) {
				buff[n++] = ' ';
			}
			break;

		case '\r':
			/* end-of-line if followed by new-line */
			if (line[i + 1] == '\n') {
				i++;
			} else {
				break;
			}
			/* fall through */
		case '\n':
			buff[n++] = '\n';
			break;

		default:
			buff[n++] = line[i];
			break;
		}
	}
	if (i < COB_MEDIUM_BUFF - 1 && buff[n - 1] != '\n') {
		cb_warning (_("File not terminated by a newline"));
		buff[n++] = '\n';
	}
	buff[n] = '\0';

	/* nothing to do anymore with free format */
	if (cb_source_format != CB_FORMAT_FIXED) {
		return n;
	}

	/* line too short */
	if (n < 8) {
		newline_count++;
		goto start;
	}

	/* check the indicator (column 7) */
	switch (buff[6]) {
	case ' ':
		bp = buff + 7;
		break;
	case '-':
		continuation = 1;
		bp = buff + 7;
		break;
	case 'd':
	case 'D':
		/* debugging line */
		if (cb_flag_debugging_line) {
			bp = buff + 7;
			break;
		}
		newline_count++;
		goto start;
#if 0
		bp = buff + 3;
		memcpy (bp, ">>D ", 4);
		break;
#endif
	case '*':
	case '/':
		/* comment line */
		newline_count++;
		goto start;
	default:
		/* invalid indicator */
		if (last_line_1 < cb_source_line - 1) {
			cb_warning (_("Invalid indicator '%c' at column 7"), buff[6]);
		}
		last_line_1 = cb_source_line;
		bp = buff + 6;
		break;
	}

	/* skip comments that follow after AUTHORS, etc. */
	if (within_comment) {
		if (buff[7] == ' ') {
			newline_count++;
			goto start;
		}
		within_comment = 0;
	}

	/* check the text that is longer than cb_text_column */
	if (n > cb_text_column + 1) {

		/* show warning if it is not whitespaces */
		if (cb_warn_column_overflow && last_line_2 < cb_source_line - 1) {
			int coln;
			for (coln = cb_text_column; coln < n; coln++) {
				if (buff[coln] != ' ' && buff[coln] != '\n') {
					cb_warning (_("Source text after column %d"),
						    cb_text_column);
					break;
				}
			}
		}

		/* remove it */
		strcpy (buff + cb_text_column, "\n");
		last_line_2 = cb_source_line;
		n = cb_text_column + 1;
	}

	/* skip blank lines */
	for (i = 7; buff[i] == ' '; i++) ;
	if (buff[i] == '\n') {
		newline_count++;
		goto start;
	}

	if (continuation) {
		/* line continuation */
		for (; *bp == ' '; bp++) ;

		/* validate concatenation */
		if (consecutive_quotation) {
			if (bp[0] == quotation_mark && bp[1] == quotation_mark) {
				bp++;
			} else {
				cb_error (_("Invalid line continuation"));
				return YY_NULL;
			}
			quotation_mark = 0;
			consecutive_quotation = 0;
		} else if (quotation_mark) {
			/* literal concatenation */
			if (*bp == quotation_mark) {
				bp++;
			} else {
				cb_error (_("Invalid line continuation"));
				return YY_NULL;
			}
		}
	} else {
		/* normal line */
		quotation_mark = 0;
		consecutive_quotation = 0;
	}

	/* check if string literal is to be continued */
	for (i = bp - buff; buff[i] != '\n'; i++) {
		if (buff[i] == '\'' || buff[i] == '\"') {
			if (quotation_mark == 0) {
				/* literal start */
				quotation_mark = buff[i];
			} else if (quotation_mark == buff[i]) {
				if (i == cb_text_column - 1) {
					/* consecutive quotation */
					consecutive_quotation = 1;
				} else {
					/* literal end */
					quotation_mark = 0;
				}
			}
		}
	}

	/* truncate trailing spaces, including the newline */
	if (quotation_mark) {
		for (; i < 72;) {
			buff[i++] = ' ';
		}
		buff[i] = 0;
	} else {
		for (i--; buff[i] == ' '; i--) ;
		if (buff[i] == '\'' || buff[i] == '\"') {
			buff[++i] = ' ';
		}
		buff[i + 1] = 0;
	}

	if (continuation) {
		strcpy (buff, bp);
		newline_count++;
	} else {
		/* insert newlines at the start of the buffer */
		memmove (buff + newline_count, bp, strlen (bp) + 1);
		memset (buff, '\n', newline_count);
		newline_count = 1;
	}

	return strlen (buff);
}

static void
ppecho (const char *text)
{
	struct cb_replace_list	*r;
	struct cb_text_list	*l;
	struct cb_text_list	*queue;

	if (text_queue == NULL && (text[0] == ' ' || text[0] == '\n')) {
		fputs (text, ppout);
	} else if (!current_replace_list) {
		for (; text_queue; text_queue = text_queue->next) {
			fputs (text_queue->text, ppout);
		}
		fputs (text, ppout);
	} else {
		/* Do replacement */

		text_queue = cb_text_list_add (text_queue, text);

		for (r = current_replace_list; r; r = r->next) {
			queue = text_queue;
			for (l = r->old_text; l; l = l->next) {
				while (l && (l->text[0] == ' ' || l->text[0] == '\n')) {
					l = l->next;
				}
				if (l == NULL) {
					break;
				}
				while (queue && (queue->text[0] == ' ' ||
				       queue->text[0] == '\n')) {
					queue = queue->next;
				}
				if (queue == NULL) {
					return;	/* partial match */
				}
				if (strcasecmp (l->text, queue->text) != 0) {
					break;
				}
				queue = queue->next;
			}
			if (l == NULL) {
				/* match */
				for (l = r->new_text; l; l = l->next) {
					fputs (l->text, ppout);
				}
/*
				text_queue = queue ? queue->next : NULL;
*/
				text_queue = queue;
				continue;
			}
		}

		/* no match */
		for (; text_queue; text_queue = text_queue->next) {
			fputs (text_queue->text, ppout);
		}
	}
}
