#line 2 "scanner.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
static yyconst short int yy_accept[405] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       68,   62,    1,    2,    7,   10,   11,   62,   61,   12,
       62,   62,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,    3,   62,   61,   12,   62,    1,
       12,   64,    1,    1,   64,   66,    1,   65,    1,   60,
        0,   12,   56,   57,   59,   58,   56,   56,   56,   56,
       56,   56,   56,    0,    0,   56,   56,   56,   56,   56,
       56,   56,   56,   56,    0,    0,    3,    0,   13,   12,
        0,   14,    1,   12,   64,    1,   63,   65,    0,   56,
       56,   56,   56,   56,   56,    0,   16,    0,   15,    0,

       56,   56,    0,   56,    0,   56,    4,   56,   56,   56,
        0,    9,    0,    8,    0,   56,    0,   41,   56,   56,
       56,    0,   56,   56,    0,    0,    0,    0,    0,   56,
       56,   56,   56,   56,    0,    0,   56,   56,   56,   56,
       56,    0,   56,   56,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   56,   56,   56,    0,   56,    0,    0,
        0,   56,    0,   56,   56,    0,   56,   56,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       56,   56,   56,    0,   56,    0,   39,    0,    0,    0,
        0,   56,   56,    0,   56,   56,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   56,    5,
        0,    0,    0,    0,    0,    0,   56,    0,   56,    6,
        0,   56,   45,    0,    0,    0,   37,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   56,    0,    0,
       48,   49,   50,   51,   52,   53,   54,   55,    0,    0,
        0,   56,    0,   56,    0,   56,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,    0,    0,    0,   20,    0,   56,    0,
       29,    0,   56,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   56,    0,    0,   56,    0,    0,    0,   35,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   25,    0,   19,   40,   18,    0,   46,   56,
       44,   21,    0,    0,    0,   43,    0,    0,    0,    0,
        0,    0,   32,    0,    0,    0,   56,    0,    0,    0,
        0,    0,    0,    0,    0,   31,    0,   28,    0,    0,
        0,   56,    0,    0,   27,    0,    0,    0,    0,    0,
       24,   17,   38,    0,    0,    0,    0,    0,    0,    0,
       23,    0,    0,   36,   42,    0,   30,    0,    0,    0,
       26,    0,    0,    0,   22,    0,   34,    0,    0,    0,

        0,    0,   47,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,    1,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   15,    1,   24,   25,
       26,   27,    1,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   38,   41,   42,   43,
       38,   44,   45,   46,   47,   48,   49,   50,   51,   52,
        1,    1,    1,    1,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   39,   40,   38,   41,
       42,   43,   38,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[53] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    2,    1,    1,    1,    8,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5
    } ;

static yyconst short int yy_base[417] =
    {   0,
        0,  933,   42,  932,   55,  931,   77,   80,  117,  145,
      936,  940,   83,  940,  940,  940,  940,  925,  940,  161,
       64,  908,   84,   75,   41,  162,   85,  180,  173,  178,
      181,  179,  187,  206,    0,  919,  918,  224,  919,  246,
      259,    0,  260,  281,  885,  940,  284,    0,  285,  940,
       80,  296,   81,  940,  940,  940,  318,  204,  310,  311,
       83,  238,  312,  924,  921,  322,  279,  330,  357,  316,
      317,  323,  328,  334,  922,  919,    0,  911,  910,    0,
      911,  910,    0,    0,    0,  362,    0,    0,  131,  324,
      240,  375,  355,  356,  344,  916,  940,  913,  940,  106,

      369,  377,  159,  389,  257,  381,  385,  386,  387,  388,
      914,  940,  911,  940,   58,  394,  395,  940,  398,  399,
      408,  880,  411,  415,  884,  456,  865,  866,  876,  417,
      419,  428,  460,  422,  880,  868,  466,  452,  474,  454,
      462,  862,  468,  478,  861,  862,  185,  866,  117,  869,
      874,  871,  851,  479,  482,  484,  164,  495,  889,  252,
      514,  278,  518,  496,  500,  864,  501,  517,  871,  534,
      867,  855,  866,  848,  537,  862,  842,  860,  848,  858,
      519,  537,  549,  846,  530,  847,  940,  851,  856,  543,
      840,  547,  544,  840,  551,  565,  843,  578,  870,  588,

      849,  852,  592,  836,  846,  835,  843,  595,  574,  587,
      601,  832,  634,  841,  833,  829,  588,  843,  594,  593,
      834,  596,  610,  839,   64,  827,  940,  825,  827,  816,
      817,  827,  829,  616,  816,  821,  626,  658,  818,  817,
      940,  940,  940,  940,  940,  940,  940,  940,  845,  824,
      823,  613,  809,  661,  812,  618,  640,  820,  810,  807,
      788,  789,  773,  775,  780,  775,  755,  758,  664,  756,
      726,  723,  940,  714,  705,  704,  940,  693,  645,  649,
      940,  654,  656,  642,  647,  674,  673,  670,  635,  613,
      607,  595,  603,  591,  566,  566,  535,  539,  530,  678,

      545,  532,  688,  521,  217,  657,  696,  520,  506,  940,
      503,  502,  701,  484,  477,  704,  455,  459,  443,  707,
      441,  430,  940,  437,  940,  940,  940,  253,  940,  699,
      940,  940,  437,  423,  408,  711,  402,  406,  715,  718,
      398,  721,  940,  394,  387,  385,  715,  391,  360,  727,
      730,  354,  344,  286,  259,  940,  257,  940,  733,  260,
      736,  738,  255,  262,  940,  214,  221,  200,  186,  742,
      940,  940,  940,  191,  199,  750,  755,  184,  758,  160,
      940,  162,  163,  940,  940,  761,  940,  152,  112,  107,
      940,  768,  102,  771,  940,   92,  940,   99,   60,   45,

      290,  359,  940,  940,  775,  783,  787,  795,  798,  802,
      809,  813,  820,  828,  836,  844
    } ;

static yyconst short int yy_def[417] =
    {   0,
      404,    1,    1,    3,    1,    5,  405,  405,  406,  406,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  407,
      404,  404,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  408,  409,  409,  407,  410,  410,
       38,  411,  404,  411,  411,  404,  404,  412,  404,  404,
      407,   38,  407,  404,  404,  404,  407,  407,  407,  407,
      407,  407,  407,  413,  414,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  415,  416,  408,  409,  409,   38,
      410,  410,   40,   41,  411,  411,  411,  412,  404,  407,
      407,  407,  407,  407,  407,  413,  404,  414,  404,  404,

      407,  407,  404,  407,  404,  407,  407,  407,  407,  407,
      415,  404,  416,  404,  404,  407,  407,  404,  407,  407,
      407,  404,  407,  407,  404,  404,  404,  404,  404,  407,
      407,  407,  407,  407,  404,  404,  407,  407,  407,  407,
      407,  404,  407,  407,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  407,  407,  407,  404,  407,  404,  404,
      404,  407,  404,  407,  407,  404,  407,  407,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      407,  407,  407,  404,  407,  404,  404,  404,  404,  407,
      404,  407,  407,  404,  407,  407,  404,  404,  404,  404,

      404,  404,  404,  404,  404,  404,  404,  404,  407,  407,
      404,  404,  404,  404,  404,  404,  407,  404,  407,  407,
      404,  407,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  407,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  407,  404,  407,  404,  407,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  407,  404,
      404,  404,  407,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  407,  404,  404,  407,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  407,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  407,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  407,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      404,  404,  404,    0,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404
    } ;

static yyconst short int yy_nxt[993] =
    {   0,
       12,   13,   14,   13,   15,   12,   15,   16,   17,   18,
       12,   13,   12,   19,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   13,   21,   12,   22,   12,   23,   24,
       25,   25,   26,   27,   25,   28,   29,   25,   25,   25,
       30,   31,   32,   25,   33,   25,   25,   25,   25,   34,
       25,   25,   36,   51,   36,   37,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   39,   40,   39,   51,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   43,   14,
       43,   43,   14,   43,   49,  401,   49,   51,   44,   54,
       55,   44,   51,   51,   49,   51,   51,   51,  135,  136,

       43,  400,   51,   43,  260,  261,   49,   51,   51,  100,
       51,   51,   51,   45,   58,   93,   45,   46,   47,   14,
       47,   46,   46,   46,   46,   46,   46,   46,   47,   57,
       46,   63,   89,   89,   89,  399,  398,  122,  396,  394,
       47,   46,   46,   46,   46,   46,   47,   14,   47,   46,
       46,   46,   46,   46,   46,   46,   47,  175,   46,  393,
      103,  103,  103,  115,  176,  157,  157,  157,   47,   46,
       46,   46,   46,   51,   51,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   64,   51,   65,  125,   51,   51,
       51,   51,   51,   51,  374,  392,  184,  390,  389,   51,

       51,  388,   59,   60,   66,   51,   51,   51,   51,   61,
       75,   62,   76,   67,   51,   71,   51,   72,   51,   68,
      328,   69,  382,   73,  386,  171,  172,  383,   70,  380,
      329,   51,   90,   51,  173,   74,   51,   78,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   49,  379,   49,
       51,   51,  117,  187,  187,  187,  328,   83,  105,  105,
      105,   49,  378,   49,  377,   51,  329,   51,   94,   49,
       81,   49,  404,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   49,   49,   49,   49,   49,   49,   49,  127,
      190,   51,   86,  402,  376,   49,   49,  375,  128,  372,

      370,  129,  369,  403,   49,   51,   51,   49,   49,  404,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   89,
       89,   89,   51,   51,   51,  100,  102,  368,   51,   51,
       51,  103,  103,  103,   51,   51,   51,   51,   51,   51,
       51,   91,   51,   51,   51,   51,   51,  107,  106,   51,
       51,   51,   95,   92,  101,   51,   51,   51,  105,  105,
      105,   51,  402,   49,  116,   49,  108,   51,   51,   51,
      110,   51,  403,   86,  121,  104,  118,  118,  118,  109,
      367,   51,   51,   51,   51,   49,  366,   51,  120,   51,
      126,  126,  126,   51,  364,  119,   51,   51,   51,   51,

       51,   51,   51,  363,   51,  124,   51,   51,   51,  123,
       51,   51,   51,   51,   51,   51,   51,  361,  132,  133,
       51,   51,   51,   51,  130,   51,   51,   51,  360,   51,
      131,   51,  137,  134,   51,   51,  138,  359,   51,  357,
       51,  140,   51,  139,   51,  354,   51,  353,  350,   51,
      154,  349,  158,  141,  144,   51,  143,  126,  126,  126,
      156,  157,  157,  157,   51,  155,   51,  161,  161,  161,
      348,  346,   51,  345,   51,  163,  163,  163,   51,   51,
       51,   51,  344,  342,  146,  162,   51,   51,  147,   51,
       51,   51,  148,   51,   51,   51,   51,  149,  165,  164,

      150,   51,  341,  340,  167,   51,   51,   51,   51,   51,
      338,   51,   51,   51,  168,  161,  161,  161,  181,  163,
      163,  163,   51,   51,  183,  182,  337,   51,   51,   51,
      185,   51,  192,  213,  195,  198,  198,  198,  203,  203,
      203,  193,   51,  335,   51,  334,   51,  333,  196,   51,
      211,  211,  211,  188,  332,   51,   51,   51,  189,   51,
      209,   51,  191,   51,   51,  327,  223,  223,  223,  210,
       51,   51,  325,  324,   51,  322,   51,   51,   51,  198,
      198,  198,  321,  320,  220,  217,   51,  222,  219,  227,
      227,  227,   51,  203,  203,  203,  237,  237,  237,   51,

       51,   51,  211,  211,  211,   51,   51,  319,   51,  318,
      225,  257,  257,  257,   51,   51,  252,  269,  269,  269,
       51,   51,  238,   51,  230,   51,  256,  237,  237,  237,
       51,  239,  317,  231,  254,  316,  232,  213,  315,  314,
       51,  257,  257,  257,  313,   51,  283,  279,  258,  241,
      242,  243,  244,  245,  246,  247,  248,   51,  272,  273,
      273,  273,  281,  281,  281,  269,  269,  269,   51,   51,
       51,  312,   51,   51,  310,  310,  310,  303,  258,  323,
      323,  323,  311,   51,   51,   51,  309,  308,   51,  326,
      326,  326,  307,  330,  305,  304,  295,  331,  331,  331,

       51,  306,  336,  336,  336,  339,  339,  339,  343,  343,
      343,   51,  351,  351,  351,   51,  339,  339,  339,  356,
      356,  356,  358,  358,  358,  302,   51,   51,  365,  365,
      365,  351,  351,  351,  371,  371,  371,  373,  373,  373,
      347,  374,   51,  381,  381,  381,  301,  355,  300,  352,
       51,  384,  384,  384,  299,  362,  385,  385,  385,  387,
      387,  387,  391,  391,  391,   51,  298,  297,  352,  395,
      395,  395,  397,  397,  397,   42,   42,   42,   42,   42,
       42,   42,   42,   48,   48,   48,   48,   48,   48,   48,
       48,   53,  296,   53,   53,   77,   77,  294,   77,   77,

       77,   77,   77,   79,   79,   82,  293,  292,   82,   85,
      291,  290,   85,   85,   85,   85,   85,   88,  289,   88,
       96,   96,  288,   96,   96,   96,   96,   96,   98,   98,
      287,   98,   98,   98,   98,   98,  111,  111,  286,  111,
      111,  111,  111,  111,  113,  113,  285,  113,  113,  113,
      113,  113,  284,  282,  280,  278,  277,  276,  275,  274,
      271,  270,  268,  267,  266,  265,  264,  263,  262,  259,
      255,  253,  251,  250,  249,  240,  236,  235,  234,  233,
      229,  228,  226,  224,  221,  218,  216,  215,  214,  212,
      208,  207,  206,  205,  204,  202,  201,  200,  199,  197,

      194,  186,  180,  179,  178,  177,  174,  170,  169,  166,
      160,  159,  153,  152,  151,  145,  142,  114,  112,   99,
       97,   81,   81,   78,   78,  114,  112,   99,   97,   87,
       81,   78,   78,   56,   50,  404,   35,   35,   35,   11,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404

    } ;

static yyconst short int yy_chk[993] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,   25,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    5,    5,    5,   25,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    7,    7,
        7,    8,    8,    8,   13,  400,   13,   24,    7,   21,
       21,    8,   51,   53,   13,   61,   23,   27,  115,  115,

        7,  399,   24,    8,  225,  225,   13,   51,   53,  100,
       61,   23,   27,    7,   24,   61,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   23,
        9,   27,   89,   89,   89,  398,  396,  100,  393,  390,
        9,    9,    9,    9,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,  149,   10,  389,
      103,  103,  103,   89,  149,  157,  157,  157,   10,   10,
       10,   10,   10,   20,   26,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   28,   29,   28,  103,   20,   26,
       30,   32,   28,   31,  374,  388,  157,  383,  382,   33,

       29,  380,   26,   26,   29,   30,   32,   28,   31,   26,
       34,   26,   34,   29,   33,   32,   58,   33,   34,   30,
      305,   31,  374,   33,  378,  147,  147,  375,   31,  369,
      305,   58,   58,   34,  147,   33,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   40,  368,   40,
       62,   38,   91,  160,  160,  160,  328,   40,  105,  105,
      105,   43,  367,   43,  366,   62,  328,   91,   62,   40,
       41,   43,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   44,   43,   44,   47,   49,   47,   49,  105,
      162,   67,   44,  401,  364,   47,   49,  363,  105,  360,

      357,  105,  355,  401,   44,  162,   67,   47,   49,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   57,
       57,   57,   59,   60,   63,   66,   67,  354,   70,   71,
       57,   68,   68,   68,   66,   72,   90,   59,   60,   63,
       73,   59,   68,   70,   71,   57,   74,   71,   70,   66,
       72,   90,   63,   60,   66,   73,   95,   68,   69,   69,
       69,   74,  402,   86,   90,   86,   72,   93,   94,   69,
       74,   95,  402,   86,   95,   68,   92,   92,   92,   73,
      353,  101,   93,   94,   69,   86,  352,   92,   94,  102,
      104,  104,  104,  106,  349,   93,  101,  107,  108,  109,

      110,  104,   92,  348,  102,  102,  116,  117,  106,  101,
      119,  120,  107,  108,  109,  110,  104,  346,  108,  109,
      121,  116,  117,  123,  106,  119,  120,  124,  345,  130,
      107,  131,  116,  110,  134,  121,  117,  344,  123,  341,
      132,  120,  124,  119,  130,  338,  131,  337,  335,  134,
      130,  334,  134,  121,  124,  132,  123,  126,  126,  126,
      132,  133,  133,  133,  138,  131,  140,  137,  137,  137,
      333,  324,  133,  322,  141,  139,  139,  139,  137,  138,
      143,  140,  321,  319,  126,  138,  139,  133,  126,  141,
      144,  154,  126,  137,  155,  143,  156,  126,  141,  140,

      126,  139,  318,  317,  143,  144,  154,  158,  164,  155,
      315,  156,  165,  167,  144,  161,  161,  161,  154,  163,
      163,  163,  158,  164,  156,  155,  314,  165,  167,  168,
      158,  181,  164,  185,  167,  170,  170,  170,  175,  175,
      175,  165,  185,  312,  168,  311,  181,  309,  168,  182,
      183,  183,  183,  161,  308,  190,  193,  185,  161,  192,
      181,  183,  163,  195,  182,  304,  196,  196,  196,  182,
      190,  193,  302,  301,  192,  299,  183,  196,  195,  198,
      198,  198,  298,  297,  193,  190,  209,  195,  192,  200,
      200,  200,  196,  203,  203,  203,  208,  208,  208,  210,

      217,  209,  211,  211,  211,  220,  219,  296,  222,  295,
      198,  223,  223,  223,  210,  217,  217,  234,  234,  234,
      220,  219,  209,  222,  203,  252,  222,  237,  237,  237,
      256,  211,  294,  203,  219,  293,  203,  213,  292,  291,
      252,  257,  257,  257,  290,  256,  256,  252,  223,  213,
      213,  213,  213,  213,  213,  213,  213,  279,  237,  238,
      238,  238,  254,  254,  254,  269,  269,  269,  283,  306,
      238,  289,  279,  254,  287,  287,  287,  279,  257,  300,
      300,  300,  288,  283,  306,  238,  286,  285,  254,  303,
      303,  303,  284,  306,  282,  280,  269,  307,  307,  307,

      303,  283,  313,  313,  313,  316,  316,  316,  320,  320,
      320,  330,  336,  336,  336,  303,  339,  339,  339,  340,
      340,  340,  342,  342,  342,  278,  330,  347,  350,  350,
      350,  351,  351,  351,  359,  359,  359,  361,  361,  361,
      330,  362,  347,  370,  370,  370,  276,  339,  275,  336,
      362,  376,  376,  376,  274,  347,  377,  377,  377,  379,
      379,  379,  386,  386,  386,  362,  272,  271,  351,  392,
      392,  392,  394,  394,  394,  405,  405,  405,  405,  405,
      405,  405,  405,  406,  406,  406,  406,  406,  406,  406,
      406,  407,  270,  407,  407,  408,  408,  268,  408,  408,

      408,  408,  408,  409,  409,  410,  267,  266,  410,  411,
      265,  264,  411,  411,  411,  411,  411,  412,  263,  412,
      413,  413,  262,  413,  413,  413,  413,  413,  414,  414,
      261,  414,  414,  414,  414,  414,  415,  415,  260,  415,
      415,  415,  415,  415,  416,  416,  259,  416,  416,  416,
      416,  416,  258,  255,  253,  251,  250,  249,  240,  239,
      236,  235,  233,  232,  231,  230,  229,  228,  226,  224,
      221,  218,  216,  215,  214,  212,  207,  206,  205,  204,
      202,  201,  199,  197,  194,  191,  189,  188,  186,  184,
      180,  179,  178,  177,  176,  174,  173,  172,  171,  169,

      166,  159,  153,  152,  151,  150,  148,  146,  145,  142,
      136,  135,  129,  128,  127,  125,  122,  113,  111,   98,
       96,   82,   81,   79,   78,   76,   75,   65,   64,   45,
       39,   37,   36,   22,   18,   11,    6,    4,    2,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,
      404,  404

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
/*							-*- c -*-
 * Copyright (C) 2001-2007 Keisuke Nishida
 * Copyright (C) 2007 Roger While
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, 51 Franklin Street, Fifth Floor
 * Boston, MA 02110-1301 USA
 */
#define YY_NEVER_INTERACTIVE 1
#line 27 "scanner.l"
#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <libcob.h>

#include "cobc.h"
#include "tree.h"
#include "parser.h"

#define SET_LOCATION(x)				\
  (x)->source_file = (unsigned char *)cb_source_file;		\
  (x)->source_line = cb_source_line

struct cb_level_78 {
	struct cb_level_78	*next;
	struct cb_field		*fld78;
};

static struct cb_level_78	*lev78ptr = NULL;
static int			last_token_is_dot = 0;
static int			integer_is_label = 0;
static int			inside_bracket = 0;

static int read_literal (char mark);
static int scan_x (char *text);
static int scan_h (char *text);
static int scan_numeric (char *text);
static int scan_picture (char *text);
static void count_lines (char *text);

#define DECIMAL_IS_PERIOD 1
#define DECIMAL_IS_COMMA 2

#define PICTURE_STATE 3
#define FUNCTION_STATE 4

#line 784 "scanner.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 65 "scanner.l"


	if (current_program) {
		if (current_program->decimal_point == '.') {
			BEGIN DECIMAL_IS_PERIOD;
		} else {
			BEGIN DECIMAL_IS_COMMA;
		}
	}

	/* We treat integer literals immediately after '.' as labels;
	   that is, they must be level numbers or section names. */
	integer_is_label = 0;
	if (last_token_is_dot) {
		integer_is_label = 1;
		last_token_is_dot = 0;
	}



#line 959 "scanner.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 405 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 940 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 85 "scanner.l"
{
	if (yytext[0] == ',' && yytext[1] == ' ' && inside_bracket) {
		return COMMA_DELIM;
	}
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 91 "scanner.l"
{ cb_source_line++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 93 "scanner.l"
{
	/* line directive */
	char *endp;

	cb_source_line = strtol (yytext + 2, &endp, 10) - 1;
	cb_source_file = strdup (strchr (endp, '"') + 1);
	strrchr (cb_source_file, '"')[0] = '\0';
}
	YY_BREAK
case 4:
#line 103 "scanner.l"
case 5:
YY_RULE_SETUP
#line 103 "scanner.l"
{ BEGIN PICTURE_STATE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 104 "scanner.l"
{ BEGIN FUNCTION_STATE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "scanner.l"
{
	/* string literal */
	return read_literal (yytext[0]);
}
	YY_BREAK
case 8:
#line 112 "scanner.l"
case 9:
YY_RULE_SETUP
#line 112 "scanner.l"
{
	/* X string literal */
	return scan_x (yytext + 2);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 117 "scanner.l"
{ inside_bracket++; return '('; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 119 "scanner.l"
{ inside_bracket--; return ')'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 121 "scanner.l"
{
	if (integer_is_label) {
		/* integer label */
		yylval = cb_build_reference (yytext);
		SET_LOCATION (yylval);
		return WORD;
	} else {
		/* numeric literal */
		return scan_numeric (yytext);
	}
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 133 "scanner.l"
{
	/* numeric literal */
	return scan_numeric (yytext);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 138 "scanner.l"
{
	/* numeric literal */
	return scan_numeric (yytext);
}
	YY_BREAK
case 15:
#line 144 "scanner.l"
case 16:
YY_RULE_SETUP
#line 144 "scanner.l"
{
	/* H numeric literal */
	return scan_h (yytext + 2);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 149 "scanner.l"
{
	count_lines (yytext);
	return SCREEN_CONTROL;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 154 "scanner.l"
{
	count_lines (yytext);
	return EVENT_STATUS;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 159 "scanner.l"
{
	count_lines (yytext);
	return BLANK_SCREEN;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 164 "scanner.l"
{
	count_lines (yytext);
	return BLANK_LINE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 169 "scanner.l"
{
	count_lines (yytext);
	return NO_ADVANCING;
}
	YY_BREAK
case 22:
#line 175 "scanner.l"
case 23:
YY_RULE_SETUP
#line 175 "scanner.l"
{	
	count_lines (yytext);
	return NOT_SIZE_ERROR;
	}
	YY_BREAK
case 24:
#line 181 "scanner.l"
case 25:
YY_RULE_SETUP
#line 181 "scanner.l"
{	
	count_lines (yytext);
	return SIZE_ERROR;
	}
	YY_BREAK
case 26:
#line 187 "scanner.l"
case 27:
YY_RULE_SETUP
#line 187 "scanner.l"
{	
	count_lines (yytext);
	return NOT_EXCEPTION;
	}
	YY_BREAK
case 28:
#line 193 "scanner.l"
case 29:
YY_RULE_SETUP
#line 193 "scanner.l"
{	
	count_lines (yytext);
	return EXCEPTION;
	}
	YY_BREAK
case 30:
#line 199 "scanner.l"
case 31:
YY_RULE_SETUP
#line 199 "scanner.l"
{	
	count_lines (yytext);
	return NOT_OVERFLOW;
	}
	YY_BREAK
case 32:
#line 205 "scanner.l"
case 33:
YY_RULE_SETUP
#line 205 "scanner.l"
{	
	count_lines (yytext);
	return OVERFLOW;
	}
	YY_BREAK
case 34:
#line 211 "scanner.l"
case 35:
#line 212 "scanner.l"
case 36:
#line 213 "scanner.l"
case 37:
YY_RULE_SETUP
#line 213 "scanner.l"
{	
	count_lines (yytext);
	return NOT_EOP;
	}
	YY_BREAK
case 38:
#line 219 "scanner.l"
case 39:
#line 220 "scanner.l"
case 40:
#line 221 "scanner.l"
case 41:
YY_RULE_SETUP
#line 221 "scanner.l"
{	
	count_lines (yytext);
	return EOP;
	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 226 "scanner.l"
{
	count_lines (yytext);
	return NOT_INVALID_KEY;
	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 231 "scanner.l"
{
	count_lines (yytext);
	return NOT_INVALID_KEY;
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 236 "scanner.l"
{
	count_lines (yytext);
	return INVALID_KEY;
	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 241 "scanner.l"
{
	count_lines (yytext);
	return INVALID_KEY;
	}
	YY_BREAK
case 46:
#line 247 "scanner.l"
case 47:
YY_RULE_SETUP
#line 247 "scanner.l"
{ /* Ignore */ }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 249 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-1");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 255 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-2");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 261 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-3");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 267 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-4");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 273 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-5");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 279 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-6");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 285 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-7");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 291 "scanner.l"
{
	yylval = cb_build_reference ("SWITCH-8");
	SET_LOCATION (yylval);
	return WORD;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 297 "scanner.l"
{
	int			token;
	struct cb_word		*word;
	struct cb_level_78	*p78;

	/* reserved word */
	token = lookup_reserved_word (yytext);
	if (token != 0) {
		yylval = 0;
		return token;
	}

	for (p78 = lev78ptr; p78; p78 = p78->next) {
		if (strcasecmp (yytext, p78->fld78->name) == 0) {
			yylval = CB_VALUE (p78->fld78->values);
			return LITERAL;
		}
	}
	/* user word */
	yylval = cb_build_reference (yytext);
	SET_LOCATION (yylval);

	/* special name handling */
	word = CB_REFERENCE (yylval)->word;
	if (word->count > 0) {
		cb_tree x = CB_VALUE (word->items);

		if (CB_SYSTEM_NAME_P (x)) {
			return MNEMONIC_NAME;
		}
	}

	return WORD;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 332 "scanner.l"
{ yylval = 0; return LE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 333 "scanner.l"
{ yylval = 0; return GE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 334 "scanner.l"
{ yylval = 0; return NE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 335 "scanner.l"
{ yylval = 0; return '^'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 336 "scanner.l"
{ last_token_is_dot = 1; yylval = 0; return '.'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 337 "scanner.l"
{ yylval = 0; return yytext[0]; }
	YY_BREAK

case 63:
YY_RULE_SETUP
#line 340 "scanner.l"
{ /* ignore */ }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 341 "scanner.l"
{
	BEGIN INITIAL;
	return scan_picture (yytext);
  }
	YY_BREAK


case 65:
YY_RULE_SETUP
#line 348 "scanner.l"
{
	BEGIN INITIAL;
	yylval = cb_build_reference (yytext);
	SET_LOCATION (yylval);
	if (strcasecmp (yytext, "TRIM") == 0) {
		return TRIM_FUNCTION;
	}
	if (strcasecmp (yytext, "NUMVAL-C") == 0) {
		return NUMVALC_FUNC;
	}
	if (strcasecmp (yytext, "LOCALE-DATE") == 0) {
		return LOCALE_DT_FUNC;
	}
	if (strcasecmp (yytext, "LOCALE-TIME") == 0) {
		return LOCALE_DT_FUNC;
	}
	return FUNCTION_NAME;
  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 366 "scanner.l"
{ yylval = 0; return yytext[0]; }
	YY_BREAK

case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DECIMAL_IS_PERIOD):
case YY_STATE_EOF(DECIMAL_IS_COMMA):
case YY_STATE_EOF(PICTURE_STATE):
case YY_STATE_EOF(FUNCTION_STATE):
#line 369 "scanner.l"
{
	last_token_is_dot = 0;
	integer_is_label = 0;
	inside_bracket = 0;
	lev78ptr = NULL;
	yyterminate ();
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 377 "scanner.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1520 "scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 405 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 405 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 404);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 377 "scanner.l"


static int
read_literal (char mark)
{
	static size_t	size = 192;
	static char	*buff = NULL;
	int		c;
	size_t		i = 0;

	if (!buff) {
		buff = cobc_malloc (size);
	}

	while ((c = input ()) != EOF) {
		buff[i++] = c;
		if (c == mark && (c = input ()) != mark) {
			i--;
			unput (c);
			break;
		}
		if (i >= size) {
			size *= 2;
			buff = realloc (buff, size);
			if (!buff) {
				fprintf (stderr, "Memory realloc failed - Aborting\n");
				fflush (stderr);
				(void)longjmp (cob_jmpbuf, 1);
			}
		}
	}
	buff[i] = 0;
	yylval = cb_build_alphanumeric_literal ((unsigned char *)buff, i);
	SET_LOCATION (yylval);
	return LITERAL;
}

static int
scan_x (char *text)
{
	static size_t		lastlen = 0;
	static unsigned char	*buff = NULL;

	unsigned char		*src = (unsigned char *)text;
	unsigned char		*dst;
	size_t			currlen;
	int			high = 1;

	currlen = strlen (text);
	if (!buff) {
		if (currlen <= COB_SMALL_BUFF) {
			buff = cobc_malloc (COB_SMALL_BUFF);
			lastlen = COB_SMALL_BUFF;
		} else {
			buff = cobc_malloc (currlen);
			lastlen = currlen;
		}
	} else {
		if (currlen > lastlen) {
			free (buff);
			buff = cobc_malloc (currlen);
			lastlen = currlen;
		} else {
			memset (buff, 0, lastlen);
		}
	}
	dst = buff;
	while (isalnum (*src)) {
		int c = toupper (*src);

		if ('0' <= c && c <= '9') {
			c = c - '0';
		} else if ('A' <= c && c <= 'F') {
			c = c - 'A' + 10;
		} else {
			goto error;
		}

		if (high) {
			*dst = c << 4;
		} else {
			*dst++ += c;
		}

		src++;
		high = 1 - high;
	}

	if (high) {
		yylval = cb_build_alphanumeric_literal ((unsigned char *)buff, dst - buff);
		SET_LOCATION (yylval);
		return LITERAL;
	}

error:
	cb_error (_("Invalid X literal: %s"), text);
	yylval = cb_error_node;
	return LITERAL;
}

static int
scan_h (char *text)
{
	unsigned char	*p;
	long long	val = 0;
	char		buff[48];

	for (p = (unsigned char *)text; *p != '\'' && *p != '\"'; p++) {
		int c = toupper (*p);

		if ('0' <= c && c <= '9') {
			c = c - '0';
		} else if ('A' <= c && c <= 'F') {
			c = c - 'A' + 10;
		} else {
			goto error;
		}

		val = (val << 4) + c;
	}

#ifdef _WIN32
	sprintf (buff, "%I64d", val);
#else
	sprintf (buff, "%lld", val);
#endif
	yylval = cb_build_numeric_literal (0, (unsigned char *)buff, 0);
	SET_LOCATION (yylval);
	return LITERAL;

error:
	cb_error (_("Invalid H literal: %s"), text);
	yylval = cb_error_node;
	return LITERAL;
}

static int
scan_numeric (char *text)
{
	int		sign, scale = 0;
	unsigned char	*s;

	/* get sign */
	sign = (*text == '+') ? 1 : (*text == '-') ? -1 : 0;
	if (sign) {
		text++;
	}

	/* get decimal point */
	s = (unsigned char *)strchr (text, current_program->decimal_point);
	if (s) {
		scale = strlen ((char *)s) - 1;
		memmove (s, s + 1, scale + 1);
	}
/*
	if (strchr (text, (current_program->decimal_point == ',') ? '.' : ',')) {
		cb_error (_("Invalid numeric literal"));
	}
*/
	if (strchr (text, '.')) {
		cb_error (_("Invalid numeric literal"));
	}
	if (strchr (text, ',')) {
		cb_error (_("Invalid numeric literal"));
	}

	yylval = cb_build_numeric_literal (sign, (unsigned char *)text, scale);
	SET_LOCATION (yylval);
	return LITERAL;
}

static int
can_replace (const char *src1, const char *src2, const size_t size,
	     const size_t iteration)
{
	const unsigned char	*p;

	if (strncasecmp (src1, src2, size)) {
		return 0;
	}
	p = (unsigned char *)src1 + size;
	if (isalnum (*p) || *p == '-' || *p == '_') {
		return 0;
	}
	if (iteration) {
		p = (unsigned char *)src1 - 1;
		if (isalnum (*p) || *p == '-' || *p == '_') {
			return 0;
		}
	}
	return 1;
}

static int
scan_picture (char *text)
{
	unsigned char		*p;
	struct cb_level_78	*p78;
	size_t			n;
	size_t			i;
	size_t			size;
	size_t			sizep;
	char			buff[COB_SMALL_BUFF];
	char			buff2[COB_SMALL_BUFF];

	/* normalize the input */
	for (p = (unsigned char *)text; *p; p++) {
		/* unput trailing '.' or ',' */
		if (p[1] == 0 && (*p == '.' || *p == ',')) {
			unput (*p);
			*p = 0;
			break;
		}
		/* upcase */
		*p = toupper (*p);
	}

	if (lev78ptr) {
		memset (buff, 0, sizeof (buff));
		memset (buff2, 0, sizeof (buff2));
		strcpy (buff, text);
		for (p78 = lev78ptr; p78; p78 = p78->next) {
			p = (unsigned char *)CB_LITERAL(CB_VALUE(p78->fld78->values))->data;
			size = strlen (p78->fld78->name);
			sizep = strlen ((char *)p);
			i = 0;
			for (n = 0; n < strlen (buff); n++) {
				if (can_replace (&buff[n], p78->fld78->name, size, n)) {
					memcpy (&buff2[i], p, sizep);
					n += size - 1;
					i += sizep;
				} else {
					buff2[i++] = buff[n];
				}
			}
			buff2[i] = 0;
			strcpy (buff, buff2);
		}
		yylval = cb_build_picture (buff2);
	} else {
		yylval = cb_build_picture (text);
	}
	return PICTURE;
}

static void
count_lines (char *text)
{
	char *p;

	for (p = text; *p; p++) {
		if (*p == '\n') {
			cb_source_line++;
		}
	}
}

void
cb_add_78 (struct cb_field *f)
{
	struct cb_level_78	*p78;

	p78 = cobc_malloc (sizeof(struct cb_level_78));
	p78->fld78 = f;
	p78->next = lev78ptr;
	lev78ptr = p78;
}

struct cb_field *
check_level_78 (const char *name)
{
	struct cb_level_78	*p78;

	for (p78 = lev78ptr; p78; p78 = p78->next) {
		if (strcasecmp (name, p78->fld78->name) == 0) {
			return p78->fld78;
		}
	}
	return NULL;
}
